"""Read back actual shared-evolve output generated by check_statler."""
import importlib.util
from pathlib import Path
import sys
import unittest
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("statler_param_reader", ROOT / "script/plot_output.py")
reader = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = reader
spec.loader.exec_module(reader)


class StatlerOutputTest(unittest.TestCase):
    def test_parameters_and_histories(self):
        for mode in ("direct", "control"):
            directory = ROOT / "output/test_statler" / mode
            self.assertTrue(directory.exists(), "run make check to generate integration fixtures")
            p = reader.read_parameters(directory)
            self.assertEqual(p["schema_version"], 2)
            self.assertEqual(p["maxSteps"], 100)
            self.assertEqual(p["N"], 500)
            self.assertEqual(p["binary_formation"], 3)
            self.assertEqual(p["direct_heating"], int(mode == "direct"))
            self.assertEqual(p["snapshot_count"], 9)
            self.assertEqual(p["history_stride"], 1)
            self.assertEqual(p["initial_timestep"], 0.001)
            self.assertEqual(p["captured_specific_energy_fraction"], 0.5)
            self.assertEqual(p["stellar_number"], 300000)
            self.assertEqual(p["stellar_radius_rsun"], 0.57)
            self.assertEqual(p["length_unit_pc"], 1.13)
            np.testing.assert_array_equal(p["initial_profile_values"], [1, 1e-12, 1e-20, 1, 1])
            np.testing.assert_allclose(p["snapshot_times_trh"][:9],
                                       [0, 1, 5, 10, 20, 13000/225, 100, 1000, 10000])
            self.assertAlmostEqual(p["time_unit_over_trh"], 2.4284946, places=6)
            self.assertGreater(p["capture_coefficient"], 0)
            times = np.fromfile(directory / "history_time_trh.dat", dtype="<f8")
            self.assertEqual(times.size, 101)
            self.assertTrue(np.all(np.diff(times) > 0))
            for file in directory.glob("history_*.dat"):
                values = np.fromfile(file, dtype="<f8")
                self.assertEqual(values.size, times.size)
                self.assertTrue(np.isfinite(values).all())


if __name__ == "__main__":
    unittest.main()
